module.exports = {
  ROOM_ID: 'ROOM_ID',
  SET_SOCKET_ID: 'SET_SOCKET_ID',
  NEW_PLAYER: 'NEW_PLAYER',
  BROADCAST_GAME_STATE: 'BROADCAST_GAME_STATE',
  START_DAMN_GAME: 'START_DAMN_GAME',
  NEW_BOARDCARD: 'NEW_BOARDCARD',
  SELECTION: 'SELECTION'
}